spring.application.name=tpl-be-springboot
spring.datasource.url=jdbc:mysql://root:FxURLjSfvALoPBrOISibbgsjWDnwMrpS@yamanote.proxy.rlwy.net:24045/railway
spring.datasource.username=root
spring.datasource.password=FxURLjSfvALoPBrOISibbgsjWDnwMrpS
spring.jpa.hibernate.ddl-auto=update
