package pe.incubadora.backend.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Persistent representation of a truck.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "camion")
public class CamionEntity {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Transport company that owns the truck. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresa_id")
    private EmpresaTransportistaEntity empresa;

    /** Unique truck plate used for identification. */
    @Column(name = "placa", unique = true)
    private String placa;

    /** Cargo type supported by the truck, such as SECA or REFRIGERADA. */
    private String tipoCarga;
    /** Maximum load capacity expressed in tons. */
    private BigDecimal capacidadToneladas;
    /** Whether the truck can participate in new operational flows. */
    private boolean activo;

}
