package pe.incubadora.backend.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Persistent representation of an operational closure.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "cierre_operativo")
public class CierreOperativoEntity {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Dock affected by the operational closure. */
    @ManyToOne
    @JoinColumn(name = "muelle_id")
    private MuelleEntity muelle;

    /** Calendar day in which the closure takes place. */
    private LocalDate fecha;
    /** Start time of the closure window. */
    private LocalTime horaInicio;
    /** End time of the closure window. */
    private LocalTime horaFin;
    /** Human-readable reason for the closure. */
    private String motivo;
    /** Closure type, such as LIMPIEZA or MANTENIMIENTO. */
    private String tipo;
}
