package pe.incubadora.backend.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import java.time.LocalDate;

/**
 * Persistent representation of a waiting queue entry.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@EntityListeners(AuditingEntityListener.class)
@Table(name = "cola_espera")
public class ColaEsperaEntity {
    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Truck waiting for a compatible dock assignment. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "camion_id")
    private CamionEntity camion;

    /** Requested service date. */
    private LocalDate fecha;
    /** Requested cargo type handled by the queue entry. */
    private String tipoCarga;
    /** Queue order, where lower values mean higher promotion priority. */
    private int prioridad;
    /** Current queue state, such as ACTIVA or ASIGNADA. */
    private String estado;
    /** Optional operational notes. */
    private String observacion;

    /** Optimistic locking version used to protect concurrent updates. */
    @Version
    private Integer version;
}
