package pe.incubadora.backend.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;


/**
 * Persistent representation of a transport company.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "empresa_transportista")
public class EmpresaTransportistaEntity {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique company tax identifier. */
    @Column(unique = true)
    private String ruc;
    /** Legal business name. */
    private String razonSocial;
    /** Main contact person name. */
    private String contactoNombre;
    /** Main contact phone number. */
    private String contactoTelefono;
    /** Contact email address. */
    private String email;
    /** Whether the company is operational in the system. */
    private boolean activo;
}
