package pe.incubadora.backend.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;

/**
 * Persistent representation of a dock.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@Table(name = "muelle")
public class MuelleEntity {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Unique business code used to identify the dock. */
    @Column(name = "codigo", unique = true)
    private String codigo;

    /** Human-readable dock name. */
    private String nombre;
    /** Cargo type accepted by the dock, including MIXTA when applicable. */
    private String tipoCargaPermitida;
    /** Maximum supported load expressed in tons. */
    private BigDecimal capacidadToneladas;
    /** Whether the dock is available for new operations. */
    private boolean activo;
}
