package pe.incubadora.backend.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;

import java.math.BigDecimal;
import java.time.Instant;
import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Persistent representation of a dock reservation.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@EntityListeners(AuditingEntityListener.class)
@Table(name = "reserva_descarga")
public class ReservaDescargaEntity {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Reserved dock. */
    @ManyToOne
    @JoinColumn(name = "muelle_id")
    private MuelleEntity muelle;

    /** Truck assigned to the reservation. */
    @ManyToOne
    @JoinColumn(name = "camion_id")
    private CamionEntity camion;

    /** Reserved calendar day. */
    private LocalDate fecha;
    /** Reservation start time. */
    private LocalTime horaInicio;
    /** Reserved duration in minutes. */
    private int duracionMin;
    /** Estimated load weight in tons. */
    private BigDecimal pesoEstimadoToneladas;
    /** Reservation lifecycle state. */
    private String estado;
    /** Business description of the goods to unload. */
    private String tipoMercaderia;
    /** Optional operator or system note. */
    private String nota;

    /** Creation timestamp managed by auditing. */
    @CreatedDate
    private Instant createdAt;

    /** Last update timestamp managed by auditing. */
    @LastModifiedDate
    private Instant updatedAt;

    /** Optimistic locking version used to protect concurrent updates. */
    @Version
    private Integer version;

}
