package pe.incubadora.backend.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.LocalDate;
import java.time.LocalTime;

/**
 * Persistent representation of a reservation slot.
 */
@Entity
@Table(name = "reserva_slots", uniqueConstraints = {
    @UniqueConstraint(
        name = "uk_muelle_fecha_hora",
        columnNames = {"muelle_id", "fecha", "hora_slot"}
    )}
)
@Data
@AllArgsConstructor
@NoArgsConstructor
public class ReservaSlotEntity {

    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Date of the occupied slot. */
    private LocalDate fecha;
    /** Start time of the occupied 30-minute slot. */
    private LocalTime horaSlot;

    /** Dock occupied by the slot. */
    @ManyToOne
    @JoinColumn(name = "muelle_id")
    private MuelleEntity muelle;

    /** Reservation that owns the slot. */
    @ManyToOne
    @JoinColumn(name = "reserva_id")
    private ReservaDescargaEntity reserva;
}
