package pe.incubadora.backend.entities;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.jpa.domain.support.AuditingEntityListener;
import pe.incubadora.backend.utils.Rol;

import java.time.LocalDateTime;


/**
 * Persistent representation of an application user.
 */
@Entity
@Data
@AllArgsConstructor
@NoArgsConstructor
@EntityListeners(AuditingEntityListener.class)
@Table(name = "usuario")
public class UsuarioEntity {
    /** Primary key generated by the database. */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;

    /** Company associated with the user when applicable. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "empresa_id")
    private EmpresaTransportistaEntity empresa;

    /** Truck associated with transport users. */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "camion_id", unique = true)
    private CamionEntity camion;

    /** Unique username used for authentication. */
    @Column(name = "username", unique = true)
    private String username;

    /** Encoded password used during authentication. */
    private String password;
    /** Assigned application role. */
    private Rol rol;
    /** Whether the user can authenticate and operate in the system. */
    private boolean activo;

    /** Creation timestamp managed by auditing. */
    @CreatedDate
    private LocalDateTime createdAt;

}
